server:
  port: 9080
  servlet:
    contextPath: /help
spring:
  application:
    name: helper-service
  datasource:
    url: jdbc:postgresql://localhost:5432/helper
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    #    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

jwt:
  secret-key: jwtkey1234567890
  exp:
    hours: 3
